layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"
route_cache: 0
template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_EXT: ".ttc" 
    COMPILE_DIR: "/tmp/ttcompile"

# broadway
broadway:
  title: "Perl Dancer"
  date: "March. 5, 2012"
  event: "Perl, Fun Again (La Cantine)"
  author: "Alexis Sukrieh"
  slides: 65
  refresh_rate: 600
  remote: 0

